name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls channel-sender/
    - name: Build the Docker image
      run: docker build . --file channel-sender/Dockerfile --tag my-image-name:$(date +%s)
